resolver: lts-19.4
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
extra-deps:
- git: https://github.com/tbidne/algebra-simple.git
  commit: 0f0c1879fc1717e39a4ae7bec22d316868c74366
nix:
  shell-file: nix/stack.nix
