name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.2.8"
          - "9.4.8"
          - "9.6.6"
          - "9.8.4"
          - "9.10.1"
          - "9.12.1"
        platform:
          - os: "macos-latest"
            set-env: "export"
          - os: "ubuntu-latest"
            set-env: "export"
          - os: "windows-latest"
            set-env: "set"
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --enable-tests --ghc-options -Werror

      - name: Compile
        run: cabal build

      - name: Doctests
        if: ${{ matrix.ghc == '9.8.4'
             || matrix.ghc == '9.10.1'
             || matrix.ghc == '9.12.1'
            }}
        run: |
          echo "*** Installing doctest ***"
          cabal install --ignore-project doctest --flag cabal-doctest

          echo "*** Running doctest ***"
          cabal doctest

      - name: Unit Tests
        run: cabal test unit --test-options '--hedgehog-tests 100000'

      - name: Configure with arithmoi
        run: cabal configure --project-file=cabal.arithmoi.project --enable-tests --ghc-options -Werror

      - name: Compile with arithmoi
        run: cabal build --project-file=cabal.arithmoi.project

      - name: Unit Tests with arithmoi
        run: cabal test unit --project-file=cabal.arithmoi.project --test-options '--hedgehog-tests 100000'

      - name: Benchmarks
        if: ${{ matrix.platform.os == 'ubuntu-latest' }}
        id: bench
        run: |
          cabal bench --project-file=cabal.arithmoi.project --benchmark-options '
            --csv benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            --svg benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.svg
            --baseline benchmarks/baseline_${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            --fail-if-slower 30
            --fail-if-faster 30'

      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.bench.conclusion == 'failure' }}
        with:
          name: build-artifacts
          path: |
            benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.csv
            benchmarks/${{ matrix.platform.os }}_${{ matrix.ghc }}_ci.svg
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
        - "macos-latest"
        - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Compile & Test
        run: nix build
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always

      #- name: HLint
      #  run: nix run .#lint
