name: "8.10.7"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal_8-10-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/1ffba9f2f683063c2b14c9f4d12c55ad5f4ed887.tar.gz

      - name: Compile
        run: |
          nix-shell nix/ghc_8-10.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always"

      - name: DocTest
        run: |
          nix-shell nix/ghc_8-10.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             RUN_DOCTEST=true cabal test doctest --test-show-details=direct"

      - name: Property Tests
        run: |
          nix-shell nix/ghc_8-10.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always && \
             MAX_RUNS=100000 cabal test props --test-show-details=direct"