name: "8.10.7"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal_8-10-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b2737d4980a17cc2b7d600d7d0b32fd7333aca88.tar.gz

      - name: Compile
        run: |
          nix-shell nix/ghc_8-10-7.nix --command \
            "cabal update && \
             cabal build --write-ghc-environment-files=always"