name: "stack"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack_yaml:
          - stack_lts-18.yaml
          - stack.yaml
          - stack_nightly.yaml
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          enable-stack: true

      - name: Compile
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
        run: stack build --ghc-options -Werror
      
      - name: Test
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
          MAX_RUNS: 100000
        run: stack test --ghc-options -Werror